// Backfire.res
// Custom res file created by RJZ for TheRatsNest to resolve an issue with player model sync on client machines
//
// items commented out are included for reference only ...
// please put this file in the valve/maps directory along with the corresponding title .bsp file


// map related files
// -----------------
maps/Backfire.res

// custom and stock models
// -----------------------
// .none

// custom and stock sprites
// ------------------------
// .none

// custom and stock sound files
// ----------------------------
// .none

// custom and stock player model files
// ----------------------------
// Base Models (v1 init - Add additional sections to this file to show updates, do NOT edit this list - RJZ)
models/player/2004man/2004man.bmp
models/player/2004man/2004man.mdl
models/player/2004man/2004man.mdl.ztmp
models/player/5burger/5burger.bmp
models/player/5burger/5burger.bmp.ztmp
models/player/5burger/5burger.mdl
models/player/5burger/5burger.mdl.ztmp
models/player/5frys/5frys.bmp
models/player/5frys/5frys.bmp.ztmp
models/player/5frys/5frys.mdl
models/player/5frys/5frys.mdl.ztmp
models/player/=$irens=Oz/=$irens=Oz.bmp
models/player/=$irens=Oz/=$irens=Oz.mdl
models/player/=$irens=Oz/=$irens=Oz.mdl.ztmp
models/player/adidas/adidas.bmp
models/player/adidas/adidas.mdl
models/player/adidas/adidas.mdl.ztmp
models/player/Alice/Alice.bmp
models/player/Alice/Alice.mdl
models/player/Alice/Alice.mdl.ztmp
models/player/Alien/hlalien.bmp
models/player/Alien/HLalien.mdl
models/player/Alien/hlalien.txt
models/player/Aquafresh/AquaFresh.BMP
models/player/Aquafresh/AquaFresh.mdl
models/player/Aquafresh/AquaFresh.txt
models/player/aquaman/aquaman.bmp
models/player/aquaman/aquaman.mdl
models/player/argentina/argentina.bmp
models/player/argentina/argentina.mdl
models/player/argentina/argentina.mdl.ztmp
models/player/b1/b1.bmp
models/player/b1/b1.mdl
models/player/b1/b1.mdl.ztmp
models/player/b1/readme.txt
models/player/BananaDancer/bananaDancer.bmp
models/player/BananaDancer/BananaDancer.mdl
models/player/BananaDancer/BananaDancer.mdl.ztmp
models/player/bananadancer/bananaDancer.bmp
models/player/bananadancer/BananaDancer.mdl
models/player/barnes_lk/barnes.bmp
models/player/barnes_lk/barnes.mdl
models/player/barnes_lk/README.TXT
models/player/barney/barney.bmp
models/player/barney/barney.mdl
models/player/Barniel/Barniel.mdl
models/player/bclinton/BClinton.bmp
models/player/bclinton/BClinton.mdl
models/player/bclinton/bclinton.mdl.ztmp
models/player/Bdroid_a/Bdroid_a.bmp
models/player/Bdroid_a/Bdroid_a.mdl
models/player/Bdroid_a/Bdroid_a.txt
models/player/Bdroid_a/Bdroid_a_logo.bmp
models/player/Bdroid_a/Bdroid_wait.ani
models/player/Bdroid_b/Bdroid_b.bmp
models/player/Bdroid_b/Bdroid_b.mdl
models/player/Bdroid_b/Bdroid_b.txt
models/player/Bdroid_b/Bdroid_b_logo.bmp
models/player/Bdroid_b/Bdroid_text.ani
models/player/Bdroid_c/Bdroid_busy.ani
models/player/Bdroid_c/Bdroid_c.bmp
models/player/Bdroid_c/Bdroid_c.mdl
models/player/Bdroid_c/Bdroid_c.txt
models/player/Bdroid_c/Bdroid_c_logo.bmp
models/player/Bender/bender.bmp
models/player/Bender/Bender.mdl
models/player/Bender/Bender.mdl.ztmp
models/player/Bender/JAN_2009.txt
models/player/Bender_ORIG/Bender_ORIG.bmp
models/player/Bender_ORIG/Bender_ORIG.mdl
models/player/Bender_ORIG/Bender_ORIG.mdl.ztmp
models/player/Bender_ORIG/Readme.txt
models/player/bert/bert.bmp
models/player/bert/bert.mdl
models/player/blue/blue.bmp
models/player/blue/blue.mdl
models/player/blue/blue.mdl.ztmp
models/player/blues/blues.bmp
models/player/blues/blues.mdl
models/player/blues/blues.txt
models/player/blueteam/blueteam.bmp
models/player/blueteam/blueteam.mdl
models/player/blueteam/blueteam.mdl.ztmp
models/player/bobafett/bobafett.bmp
models/player/bobafett/bobafett.mdl
models/player/bobafett/Readme.txt
models/player/brazil/brazil.bmp
models/player/brazil/brazil.mdl
models/player/brazil/brazil.mdl.ztmp
models/player/bundeswehr/Bundeswehr.BMP
models/player/bundeswehr/Bundeswehr.mdl
models/player/bundeswehr/bundeswehr.mdl.ztmp
models/player/bundeswehr1/Bundeswehr1.BMP
models/player/bundeswehr1/Bundeswehr1.mdl
models/player/bundeswehr1/bundeswehr1.mdl.ztmp
models/player/cannon_guy/Cannon_Guy.bmp
models/player/cannon_guy/cannon_guy.bmp.ztmp
models/player/cannon_guy/cannon_guy.mdl
models/player/cannon_guy/cannon_guy.mdl.ztmp
models/player/cannon_guy/Cannon_Guy.txt
models/player/cannon_guy/cannon_guy.txt.ztmp
models/player/chrome/chrome.bmp
models/player/chrome/chrome.mdl
models/player/chrome/chrome.mdl.ztmp
models/player/colonel_sanders/colonel_sanders.bmp
models/player/colonel_sanders/colonel_sanders.mdl
models/player/daffy/daffy.bmp
models/player/daffy/daffy.mdl
models/player/daffy/daffy.mdl.ztmp
models/player/darth_maul/1.JPG
models/player/darth_maul/2.JPG
models/player/darth_maul/3.JPG
models/player/darth_maul/4.JPG
models/player/darth_maul/Darth-Maul.mdl
models/player/darth_vader/DarthVader.mdl
models/player/derposaur/derposaur.mdl
models/player/derposaur/derposaur.mdl.ztmp
models/player/derpx0r/derpx0r.mdl
models/player/derpx0r/derpx0r.mdl.ztmp
models/player/dfa/dfa.bmp
models/player/dfa/dfa.mdl
models/player/dfa/dfa.mdl.ztmp
models/player/dfa/readme.txt
models/player/dildo/dildo.bmp
models/player/dildo/dildo.mdl
models/player/dildo/dildo.mdl.ztmp
models/player/dildo/dildo.txt
models/player/drake/drake.BMP
models/player/drake/drake.mdl
models/player/drake/drake.mdl.ztmp
models/player/drake/Drake.txt
models/player/duke_nukem/duke.bmp
models/player/duke_nukem/duke.mdl
models/player/d_v/d_v.mdl
models/player/d_v/d_v.mdl.ztmp
models/player/elvis/elvis.bmp
models/player/elvis/elvis.mdl
models/player/elvis/elvis.mdl.ztmp
models/player/elvis/elvis.txt
models/player/gibbed/Gibbed.bmp
models/player/gibbed/Gibbed.mdl
models/player/gibbed/gibbed.mdl.ztmp
models/player/gibbed/gibbed.txt
models/player/Giggles/Giggles.bmp
models/player/Giggles/Giggles.mdl
models/player/Giggles/Giggles.txt
models/player/gina/gina.bmp
models/player/gina/Gina.mdl
models/player/gman/gman.BMP
models/player/gman/Gman.mdl
models/player/gordon/gordon.bmp
models/player/gordon/gordon.mdl
models/player/goth/goth.bmp
models/player/goth/goth.mdl
models/player/goth/goth.mdl.ztmp
models/player/greyfox/GreyFox.bmp
models/player/greyfox/GreyFox.mdl
models/player/greyfox/greyfox.mdl.ztmp
models/player/greyfox/GreyFox.txt
models/player/grinch/Grinch.bmp
models/player/grinch/Grinch.mdl
models/player/grinch/grinch.mdl.ztmp
models/player/grinch/Grinch.txt
models/player/helmet/helmet.bmp
models/player/helmet/Helmet.mdl
models/player/hgrunt/hgrunt.bmp
models/player/hgrunt/Hgrunt.mdl
models/player/homer/homer.bmp
models/player/homer/homer.mdl
models/player/homer/homer.mdl.ztmp
models/player/homer/README.TXT
models/player/i/i.bmp
models/player/i/i.mdl
models/player/i/i.mdl.ztmp
models/player/iron_man/Iron Man.mdl
models/player/Jason/Jason.bmp
models/player/Jason/jason.mdl
models/player/Jason/Jason.mdl.ztmp
models/player/Jesus/Jesus.bmp
models/player/Jesus/Jesus.mdl
models/player/Jesus/Jesus.txt
models/player/Kate/Kate .mdl
models/player/lain/lain.bmp
models/player/lain/lain.mdl
models/player/lain/lain.mdl.ztmp
models/player/lego/lego.bmp
models/player/lego/lego.mdl
models/player/luigi/Luigi.bmp
models/player/luigi/luigi.bmp.ztmp
models/player/luigi/Luigi.mdl
models/player/luigi/luigi.mdl.ztmp
models/player/luigi/Luigi.txt
models/player/luigi/luigi.txt.ztmp
models/player/mario/mario.bmp
models/player/mario/mario.bmp.ztmp
models/player/mario/mario.mdl
models/player/mario/mario.mdl.ztmp
models/player/mario/Mario.txt
models/player/mario/mario.txt.ztmp
models/player/max_payne/payne.bmp
models/player/max_payne/payne.mdl
models/player/momia/momia.bmp
models/player/momia/momia.mdl
models/player/momia/momia.mdl.ztmp
models/player/mrpeanut/mrpeanut.bmp
models/player/mrpeanut/mrpeanut.mdl
models/player/mrpeanut/mrpeanut.mdl.ztmp
models/player/mrpeanut/Thumbs.db
models/player/muerte/muerte.bmp
models/player/muerte/muerte.mdl
models/player/muerte/muerte.mdl.ztmp
models/player/nympho/nympho.mdl
models/player/nympho/nympho.mdl.ztmp
models/player/pantera/pantera.bmp
models/player/pantera/pantera.mdl
models/player/pantera/pantera.mdl.ztmp
models/player/partybear/PartyBear.bmp
models/player/partybear/partybear.mdl
models/player/partybear/samuri1.avi
models/player/penguins/penguins.bmp
models/player/penguins/penguins.mdl
models/player/peruano/peruano.bmp
models/player/peruano/peruano.mdl
models/player/peruano/peruano.mdl.ztmp
models/player/picard/picard.mdl
models/player/picard/picard.mdl.ztmp
models/player/pink_panther/pink_panther.bmp
models/player/pink_panther/pink_panther.mdl
models/player/pink_panther/readme.txt
models/player/rangers/rangers.bmp
models/player/rangers/rangers.mdl
models/player/raptor/raptor.bmp
models/player/raptor/raptor.mdl
models/player/raptor/raptor.txt
models/player/recon/recon.bmp
models/player/recon/recon.mdl
models/player/red/red.bmp
models/player/red/red.mdl
models/player/red/red.mdl.ztmp
models/player/robo/Robo.bmp
models/player/robo/robo.mdl
models/player/ROBOCOP3/ROBOCOP3.bmp
models/player/ROBOCOP3/ROBOCOP3.mdl
models/player/ROBOCOP3/ROBOCOP3.mdl.ztmp
models/player/ROBOCOP3/Thumbs.db
models/player/ronny/readme.txt
models/player/ronny/ronny.bmp
models/player/ronny/ronny.mdl
models/player/ronny/ronny.mdl.ztmp
models/player/santa_hd/santa_hd.bmp
models/player/santa_hd/santa_hd.mdl
models/player/scientist/Scientist.bmp
models/player/scientist/Scientist.mdl
models/player/scream/Scream.bmp
models/player/scream/Scream.mdl
models/player/scream/scream.mdl.ztmp
models/player/Snickers/player
models/player/Snickers/Snickers.bmp
models/player/Snickers/Snickers.mdl
models/player/Snickers/Snickers.mdl.ztmp
models/player/Snickers/player/Snickers
models/player/Snickers/player/Snickers/Snickers.bmp
models/player/Snickers/player/Snickers/Snickers.mdl
models/player/spawn/readme.txt
models/player/spawn/Spawn.bmp
models/player/spawn/Spawn.mdl
models/player/spawn/spawn.mdl.ztmp
models/player/srobo/GameCfg.wc
models/player/srobo/srobo.bmp
models/player/srobo/srobo.mdl
models/player/srobo/srobo.mdl.ztmp
models/player/Stormtrooper/Stormtrooper.mdl
models/player/Stormtrooper/Stormtrooper.mdl.ztmp
models/player/Stormtroop_Agi/Stormtrooper.txt
models/player/Stormtroop_Agi/Stormtroop_Agi.BMP
models/player/Stormtroop_Agi/Stormtroop_Agi.mdl
models/player/T3/T3.bmp
models/player/T3/T3.mdl
models/player/T3/T3.mdl.ztmp
models/player/tigger/tigger.bmp
models/player/tigger/tigger.mdl
models/player/wolverine/wolverine.bmp
models/player/wolverine/wolverine.mdl
models/player/wolverine/wolverine.mdl.ztmp
models/player/wolverine/wolverine2.bmp
models/player/wolverine/wolverine_README.txt
models/player/zombie/zombie.bmp
models/player/zombie/zombie.mdl
